id: P80484769
initial_creation_type: input
source_metadata:
  title: 'MSV 6,09: Māṇavikā'
  language: sa
  volumes:
    f97f112afcb94e218dab4dc2e9b4ccbe:
      title: Māṇavikā
      base_file: Māṇavikā.txt
      work_id: W2973F7C6
  chapter_to_tile: {}
created_at: '2022-03-01T22:57:31.925615'
last_modified_at: '2022-03-01T22:57:31.925622'
